version: '3.4'

services:
  generatinggreetings:
    image: generatinggreetings
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8989:8989
